### ISSUE TITLE
can not delete account

### ISSUE THREAD

**Issue by balakirevs** [ziptofaf/gdpr-rails#5]
Hi, could you please add possibility to "Cancel my account" (currently there is an error in application) by removing only encryption key just to keep data in db as you mention in your blog?

Many thanks!

**Comment by ziptofaf** [comment]
Hello, I actually can't reproduce your issue. 

Going to /users/edit and clicking on 'cancel my account' does not cause errors on my end, it deletes account correctly. What it does NOT delete is an encryption key connected to said account but frankly I am not even sure it should do that (since it's kept in a separate database which can have a different backup policy and whatnot, I would rather not automate this). 

If you want custom logic regarding it then best idea would be to implement it yourself. Simply getting rid of user's encryption key is basically this:

    user = User.first
    redis = Redis::Namespace.new(:encrypt, :redis => Redis.new)
    key = user.id.to_s
    redis.del(key)

This will cause trying to access user's email afterwards to display '[deleted]' and make a whole object pretty much immutable (I suggest against trying to call .save on it, although I have described in my blog on how to change that). Destroying still works just fine however.

**Comment by balakirevs** [comment]
Thanks
